### ISSUE TITLE
msm8937: KGSL doesn't work and sometimes makes kp when tries to load fw

### ISSUE THREAD

**Issue by MrArtemSid** [Necromancer-team/msm-4.19#1]
KGSL on A505 doesn't wanna work, meanwhile on msm8917(a308) works fine

Issue:
[   15.710098] kgsl kgsl-3d0: CP initialization failed to idle
[   15.710130] kgsl kgsl-3d0: rb=0 pos=0/9 rbbm_status=800001C1/00000000 int_0_status=00800000
[   15.710140] kgsl kgsl-3d0:  hwfault=00000000

ramoops link:
https://gist.github.com/MrArtemSid/52209b0f64c84ba1abccc1e5c96bb7b0

**Comment by MrArtemSid** [comment]
another log from Xiaomi Redmi 4X (santoni)
https://gist.github.com/MrArtemSid/bfb0181d8cd1a52704a52d17b5ed05c9

**Comment by tattwamashi** [comment]
https://github.com/Atom-X-Devs/android_kernel_xiaomi_sdm660/commit/59f6d7db3a68b25ebcfb2f424ea591465b78f4b5#diff-a0ef6d5f001bb7b32dda89f472249110e88cbe4aa5bb3a3e6623bbb2dde2bb0a

Try this.. we need this revert as we dont have that new gpu firmware hence it crashes... Tested on asus, xiaomi 4.19 kernels on our org @Atom-X-Devs

Edit:- I reviewed your commit history in default branch and its missing this commit. Our stock kernel revisions also have this change btw.. so its indeed needed

**Comment by MrArtemSid** [comment]
@ElectroPerf I tried reverting this, it didn't help at all. We tried different combinations of fw, since msm8937 device doesn't have adreno fw signed

**Comment by wiktorek140** [comment]
Hmm, this seems interesting.

[   11.807139] can't get fw name.

Maybe its from gpu driver? Its not catching proper file so it fail to load and crash. Something like race condition between gpu driver and mounting partition.

Proably like that becuse of these logs:

kgsl kgsl-3d0: Falling back to syfs fallback for: a530_pm4.fw
[   13.694686] kgsl kgsl-3d0: Falling back to syfs fallback for: a530_pfp.fw

**Comment by MrArtemSid** [comment]
kgsl kgsl-3d0: Falling back to syfs fallback for: a530_pm4.fw
[ 13.694686] kgsl kgsl-3d0: Falling back to syfs fallback for: a530_pfp.fw

This happens even on sdm660, so we can ignore that

can't get fw name. It's from sensors as far as I remember

**Comment by MrArtemSid** [comment]
Fixed by:
https://github.com/Necromancer-team/msm-4.19/commit/6503735864d1cd1c13ae68c5b5d6738f56a7647e
https://github.com/Necromancer-team/msm-4.19/commit/92e96e357e1c49fc0d0f0956f651abe016847e61
https://github.com/Necromancer-team/msm-4.19/commit/32874a34b12d3f1153fe8c240637c97ddf86ea0c
